version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REGISTRY: ${REGISTRY:-ghcr.io/imgoptify/resmush-unleashed}
    volumes:
      - ./src/:/var/www/html
    environment:
      - ENV_REMOTE_SERVER_DOMAIN=127.0.0.1
      - ENV_REMOTE_SERVER_PROTOCOL=http
      - ENV_REMOTE_KEY_FULL_RESPONSE=DEADBEEFDEADBEEFDEADBEEFDEADBEEF
      - ENV_MAX_FILESIZE=26214400
      - ENV_JPEGOPTIM_LEVEL=92
      - ENV_WEBPMINORFACTOR_LEVEL=0.85
      - ENV_DISK_USAGE_THRESHOLD=90
    ports:
    - "80:80"
